### ISSUE TITLE
Minified javascript with classnames

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#17] opened 2017-05-27 00:27 UTC
I've narrowed down why classnames in my 1Mb minified javascript bundle are [not replaced](https://github.com/JPeer264/node-rcs-core/issues/8#issuecomment-304160629) with renamed ones.
`AttributeList_table_vdlBA` and `AttributeList_key_3npMX` are classnames.
```javascript
function(e,t){e.exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"},function(e,t){e.exports={table:"AttributeList_table_vdlBA",key:"AttributeList_key_3npMX"}}
```
==>
```javascript
function(e,t){e.exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"},function(e,t){e.exports={table:"AttributeList_table_vdlBA",key:"AttributeList_key_3npMX"}}
```
If I put line brake between two functions, replacement gets back to normal
```javascript
function(e,t){e.exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"},
function(e,t){e.exports={table:"AttributeList_table_vdlBA",key:"AttributeList_key_3npMX"}}
```
==>
```javascript
function(e,t){e.exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"},
function(e,t){e.exports={table:"nM",key:"iH"}}
```

**Comment by JPeer264** [comment] 2017-05-27 07:05
I see. This is bug is not in `rcs-core` it is in `rename-css-selectors`. I will check where the problem is.

**Comment by JPeer264** [comment] 2017-05-27 07:37
This should be fixed @klimashkin. Thanks again for reporting these bugs!

**Closed** 2017-05-27 07:37 UTC
Labels: bug
